services:
  hub:
    image: selenium/hub:4.27
  chrome:
    image: selenium/node-chromium:4.27
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=5
    shm_size: "2g"
  firefox:
    image: selenium/node-firefox:4.27
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=5
    shm_size: "2g"
  vendor-portal:
    image: babosina/selenium-java
    depends_on:
      - chrome
    environment:
      - BROWSER=chrome
      - hubHost=hub
      - THREAD_COUNT=5
      - TEST_SUITE=vendor-portal.xml
    volumes:
      - ./output/vendor-portal:/home/selenium-docker/test-output
  flight-reservation:
    image: babosina/selenium-java
    depends_on:
      - firefox
    environment:
      - BROWSER=firefox
      - hubHost=hub
      - THREAD_COUNT=5
      - TEST_SUITE=flight-reservation.xml
    volumes:
      - ./output/flight-reservation:/home/selenium-docker/test-output